
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-16
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-16
pull_requests: [{"author":{"id":"MDQ6VXNlcjY4Mjk4MzE1","is_bot":false,"login":"JackLiu8","name":""},"headRefName":"Jack-CommonsFeaturesEnumClean","number":72,"title":"Remove extra CommonsFeatures enum values","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/72"},{"author":{"id":"U_kgDOCusDGg","is_bot":false,"login":"ikeacat2","name":"Ivy Holiday"},"headRefName":"announcements/create-page","number":70,"title":"Issues #60 & 61 (subissues) Add Announcement Table and Add Functional Create Page to Announcements","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/70"},{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-FixCourseTableStorybookFromOldGroup","number":59,"title":"JS-fix course table storybook from old group","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/59"},{"author":{"id":"U_kgDOCuipXA","is_bot":false,"login":"nikitahuynh","name":""},"headRefName":"nh-create-dashboard-button","number":58,"title":"Dashboard Subissue: Create a Dashboard Button","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/58"},{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-AddFormForCourses-BranchedOffPrevious","number":56,"title":"Issue #40: Add Form for Courses","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/56"},{"author":{"id":"MDQ6VXNlcjY4Mjk4MzE1","is_bot":false,"login":"JackLiu8","name":""},"headRefName":"Jack-AnnouncementsOnPlayPage","number":55,"title":"added current announcements to play page","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/55"}]
