
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-16
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-16
pull_requests: [{"author":{"id":"U_kgDOCVIPTg","is_bot":false,"login":"sharanya444","name":"sharanya gehlot"},"headRefName":"feature-flags","number":47,"title":"feat: add featureFlags to SystemInfo for feature flag support (closes…","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/47"},{"author":{"id":"U_kgDOCuipXA","is_bot":false,"login":"nikitahuynh","name":""},"headRefName":"update_jdsom","number":45,"title":"ran npm install -D jsdom@16.7.0","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/45"},{"author":{"id":"U_kgDOCuipXA","is_bot":false,"login":"nikitahuynh","name":""},"headRefName":"NH-allow-admin-see-commons-chat","number":44,"title":"add button and working duplication of chathistorypage","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/44"},{"author":{"id":"U_kgDOCusDGg","is_bot":false,"login":"ikeacat2","name":"Ivy Holiday"},"headRefName":"feature/launcher","number":43,"title":"Issue #28: Add launcher for /api/jobs/launch/recordcommonstats to Admin Jobs page","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/43"}]
