
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/proj-happycows-s26-16
owner: ucsb-cs156-s26
repo_name: proj-happycows-s26-16
pull_requests: [{"author":{"id":"U_kgDOCu1aKQ","is_bot":false,"login":"RohilJainUCSB","name":""},"headRefName":"rj-hidden-commons-exception","number":82,"title":"RJ - Added the HiddenCommonsException to prevent API calls from execuing on hidden commons","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/82"},{"author":{"id":"U_kgDOCv6zKw","is_bot":false,"login":"JohnDSylvester","name":"John Sylvester"},"headRefName":"JS-ChangeTableImplementationToMatch","number":80,"title":"JS- Changed Courses Table Implementation To Match Other Tables","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/80"},{"author":{"id":"U_kgDOCusDGg","is_bot":false,"login":"ikeacat2","name":"Ivy Holiday"},"headRefName":"announcements/create-page","number":70,"title":"Issues #60 & 61 (subissues) Add Announcement Table and Add Functional Create Page to Announcements","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/70"},{"author":{"id":"MDQ6VXNlcjY4Mjk4MzE1","is_bot":false,"login":"JackLiu8","name":""},"headRefName":"Jack-AnnouncementsOnPlayPage","number":55,"title":"added current announcements to play page","url":"https://github.com/ucsb-cs156-s26/proj-happycows-s26-16/pull/55"}]
